name: wisata_candi
description: "Aplikasi Wisata Candi"

version: 1.0.0+1

environment:
  sdk: ^3.4.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
